### ISSUE TITLE
Package for Illustrator doesn't work ?

### ISSUE THREAD

**Issue by SheepDomination** [seblavoie/After-Effects-Scripting-Sublime-Text-Package#12]
Hi, I couldn't get the [Sublime Package for Illustrator](https://github.com/SableRaf/Illustrator-Scripting-Sublime-Text-Package) to work within Sublime Text 2 ?

**Comment by ff6347** [comment]
Maybe you should ask the original author for assistance (not an issue)

**Comment by seblavoie** [comment]
Yes, https://github.com/SableRaf/Illustrator-Scripting-Sublime-Text-Package is a fork of my repo. The author (@SableRaf) will be the one to contact. Unfortunately the fork doesn't accept issues, so you will have to contact the author outside of Github.

**Comment by SheepDomination** [comment]
The author doesn't except issues; therefore how can I contact the author ?

**Comment by seblavoie** [comment]
He will get a notification from this issue thread since I tagged him. Also, I googled his name and found his [Twitter](https://twitter.com/sableraph?lang=en), you might want to message him there.

**Comment by SheepDomination** [comment]
I'm not on Twitter.  I can only hope he gets this notification.
