### ISSUE TITLE
Adobe CC 2017 - win10 64bits

### ISSUE THREAD

**Issue by matinhus** [seblavoie/After-Effects-Scripting-Sublime-Text-Package#13]
Hello! @seblavoie

Having some problems with build command. Receiving this msg: 

> not recognized as an internal or external command in Windows

This happens when its runs **AfterFX -r** (I think, in Windows u have to put the extension .exe, I'm not sure).

I got it to run typing the whole path of AE in the .bat file. But then another problem. When I run the build, its open, execute the script and then close AE, do not keep the program opened. Using the Adobe Scripting tool the same code works fine and AE keeps opened. Any clues how to solve those issues?

Thanks in advance!

**Comment by seblavoie** [comment]
I built this package quite a while ago on Windows 7 and don't have access to a Windows environment at the moment. The last contribution concerning Windows was made by @BrownBichon who perhaps might be able to answer your question. 

Other than that I am a little out of my depth. Sorry about that.

**Comment by BrownBichon** [comment]
I just saw the notification. Then I tested on my PC with CC2015 and Win10 64bits, it works fine.
Maybe try this [How to fix "not recognized as internal or external" in cmd](https://www.youtube.com/watch?v=5AszIAz4PSI), hope it will help.

**Comment by matinhus** [comment]
Thanks, @BrownBichon, @seblavoie  !
Any clue about the AE closes after the script runs?

**Comment by matinhus** [comment]
I have found a workaround: include the path of AE (%programfiles%\Adobe\Adobe After Effects CC 2017\Support Files) at Environment Variables.

Also, to avoid AE to close (after running a script), I have run the build with AE opened.

That's it. Thanks again!

**Comment by seblavoie** [comment]
Great! Glad you found a solution 👍
