### ISSUE TITLE
[windows] file path error

### ISSUE THREAD

**Issue by fynnay** [seblavoie/After-Effects-Scripting-Sublime-Text-Package#7]
Hey man, thanks a lot for this. Works like a charm on my mac.
On windows, however, I keep getting this error:
<code>
The filename, directory name, or volume label syntax is incorrect.
[Finished in 0.0s with exit code 1]
[cmd: ['cd C:\\Users\\postyr\\AppData\\Roaming\\Sublime Text 3\\Packages\\AfterEffects\\ && build.bat testing.jsx D:\\FYNN\\scripting\\after_effects\\testing']]
[dir: D:\FYNN\scripting\after_effects\testing]
[path: C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Autodesk\Backburner\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files (x86)\Skype\Phone\]
</code>

Id did try @ZombieHippie 's solution in Issue#4. But to no avail.

**Comment by seblavoie** [comment]
I have not work with windows for a while, but I see `D:\FYNN\scripting\after_effects\testing`, do you have your script on an external drive? I'm not sure but this may be causing some issues.

**Comment by fynnay** [comment]
No, it's an internal drive, but not the windows install drive. I have tried copying my script to the C:\\ drive and building from there, but no success.

**Comment by seblavoie** [comment]
I won't be able to give good support on this one as I don't have access to a windows environment. Let me know if you find anything.

**Comment by fynnay** [comment]
Alright. I'm in contact with @ZombieHippie . I'll post the solution here as soon as there is one.

**Comment by ZombieHippie** [comment]
@fynnay Check out my repository: https://github.com/ZombieHippie/sublime-text-2-ExtendScript which I have just updated for greater flexibility.

Otherwise, it looks like that space here `cd C:\Users\postyr\AppData\Roaming\Sublime Text 3\Packages\AfterEffects\` between `Sublime` and `Text` will separate those as arguments.
